Repository siderolabs/kres, pull requests merged in 2024-03, with the labels that each got.

#357 chore: support more customization
  internal/output/dockerfile/stage.go
  internal/output/dockerfile/step/copy.go
  internal/project/common/docker.go
  internal/project/common/image.go
  internal/project/custom/custom.go
  internal/project/golang/toolchain.go
Labels: status/ok-to-test, status/ok-to-merge

#358 chore: support more customization for Pkgfile
  internal/project/golang/toolchain.go
  internal/project/pkgfile/build.go
Labels: status/ok-to-test, status/ok-to-merge

#363 chore: bump deps
  .github/workflows/ci.yaml
  Dockerfile
  Makefile
  go.mod
  go.sum
  internal/config/constants.go
  internal/output/files.go
  internal/output/github/github.go
  internal/project/common/repository.go
  internal/project/golang/toolchain.go
  internal/project/pkgfile/build.go
Labels: status/ok-to-test, status/ok-to-merge

#364 fix: dockerfile preamble handling
  internal/output/files.go
Labels: status/ok-to-test, status/ok-to-merge

#365 chore: bump bldr to v0.3.0
  internal/config/constants.go
Labels: status/ok-to-test, status/ok-to-merge

#366 fix: make `TAG` getter select only tags starting with `v` prefix
  Makefile
  internal/project/common/build.go
Labels: status/ok-to-test, status/ok-to-merge

#367 fix: buildx setup
  .github/workflows/ci.yaml
  internal/output/ghworkflow/gh_workflow.go
Labels: status/ok-to-test, status/ok-to-merge

#369 feat: bump gh actions buildx setup timeout minutes
  .github/workflows/ci.yaml
  internal/output/ghworkflow/gh_workflow.go
Labels: status/ok-to-test, status/ok-to-merge

#371 fix: git repo handling
  internal/project/auto/golang.go
  internal/project/auto/pkgfile.go
  internal/project/common/docker.go
Labels: status/ok-to-test, status/ok-to-merge

#372 chore: bump stuff
  .github/workflows/ci.yaml
  .golangci.yml
  Dockerfile
  Makefile
  go.mod
  go.sum
  internal/config/constants.go
  internal/output/files.go
  internal/output/golangci/golangci.yml
  internal/project/common/input_image.go
  internal/project/golang/golangcilint.go
  internal/project/js/eslint.go
  internal/project/js/templates/templates.go
  internal/toposort/toposort.go
Labels: status/ok-to-test

#373 fix: Allow repository owner to contains uppercase characters
  internal/project/pkgfile/build.go
Labels: status/ok-to-merge
